### ISSUE TITLE
Figma Design Preview

### ISSUE THREAD

**Issue by EliasProjects** [chas-academy/u05-imdb-klon-grupp-6#46]
https://www.figma.com/file/RPF1wLU8HLJJNxbIX7bHix/Open-Fashion---Free-eCommerce-UI-Kit-(Community)?type=design&node-id=1002%3A2639&mode=design&t=nWcl7d7KxVU7yfFR-1

**Comment by Sebah7** [comment]
I like the color palate. 💯 
Wish the background is less blurry. 
Please work on this link so we all can share and comment(low - fi sets there): [Figma](https://www.figma.com/file/F5yEJOMn965gSscTSkxvey/U05_IMDb_Klon?type=design&node-id=0%3A1&mode=design&t=DZOKr0aU76Wbrp9m-1)
